apiVersion: v1
kind: ConfigMap
metadata:
  name: account-app-config
  namespace: iput-kernel-foundation
data:
  SMTP_HOST: "mail"
  SMTP_PORT: "465"
  SMTP_USERNAME: "noreply@iput-kernel.com"

  REDIS_HOST: "account-worker"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  DB_HOST: "account-db"
  DB_USER: "root"
  DB_NAME: "account"
  DB_PORT: "5432"
  DB_SSLMODE: "require"

  CRED_DEFAULT: 10
  CRED_LEVEL1: 0
  CRED_LEVEL2: 256
  CRED_LEVEL3: 512
  CRED_LEVEL4: 1024
  CRED_LEVEL5: 2048